import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ScrollReveal from '@/components/ScrollReveal';
import SEO, { schemas } from '@/components/SEO';

const Privacy = () => {
  return (
    <div className="min-h-screen bg-background">
      <SEO 
        title="Privacy Policy"
        description="Privacy Policy for AERELION Systems. We process data only to deliver services. We never sell your data."
        canonicalUrl="/privacy"
        structuredData={schemas.breadcrumb([
          { name: 'Home', url: '/' },
          { name: 'Privacy', url: '/privacy' }
        ])}
      />
      <Navbar />
      
      <main className="pt-24">
        <section className="section-padding">
          <div className="container-main max-w-3xl">
            <ScrollReveal>
              <h1 className="font-display text-4xl md:text-5xl mb-6">
                Privacy Policy
              </h1>
              <p className="text-muted-foreground mb-10">
                Last updated: January 2026
              </p>
            </ScrollReveal>

            <ScrollReveal delay={0.1}>
              <div className="prose prose-invert max-w-none space-y-10">
                
                <section>
                  <h2 className="font-display text-xl mb-3">How We Operate</h2>
                  <p className="text-muted-foreground">
                    AERELION Systems is a service provider that installs and operates automation 
                    workflows on behalf of clients. We access your systems only to deliver agreed 
                    services—nothing more.
                  </p>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">What We Collect</h2>
                  <ul className="list-disc list-inside text-muted-foreground space-y-2">
                    <li><strong>Engagement information:</strong> Name, email, company details submitted through our intake form.</li>
                    <li><strong>Credentials:</strong> Access tokens and API keys you provide to enable workflow operation.</li>
                    <li><strong>Operational data:</strong> Logs and metrics generated by running workflows.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">How We Use Data</h2>
                  <ul className="list-disc list-inside text-muted-foreground space-y-2">
                    <li>To install, configure, and operate workflows on your behalf.</li>
                    <li>To troubleshoot issues and improve workflow performance.</li>
                    <li>To communicate about your engagement and provide support.</li>
                  </ul>
                  <p className="text-muted-foreground mt-3">
                    <strong>We do not sell, share, or monetize your data.</strong>
                  </p>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">Credential Security</h2>
                  <ul className="list-disc list-inside text-muted-foreground space-y-2">
                    <li>Credentials are encrypted at rest using industry-standard encryption.</li>
                    <li>We request least-privilege access—only what's needed for the workflow.</li>
                    <li>You can revoke access at any time through your tool's settings.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">Data Retention</h2>
                  <p className="text-muted-foreground">
                    We retain operational data only as long as needed to run your workflows. 
                    Logs are regularly purged. After an engagement ends, credentials are deleted 
                    unless you request ongoing monitoring services.
                  </p>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">Your Rights</h2>
                  <ul className="list-disc list-inside text-muted-foreground space-y-2">
                    <li>Request a summary of data we hold about your engagement.</li>
                    <li>Request deletion of your data after engagement ends.</li>
                    <li>Revoke access to connected accounts at any time.</li>
                  </ul>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">Third-Party Tools</h2>
                  <p className="text-muted-foreground">
                    Workflows may integrate with third-party services (CRM, email, etc.). 
                    Those services have their own privacy policies. We encourage you to review them.
                  </p>
                </section>

                <section>
                  <h2 className="font-display text-xl mb-3">Contact</h2>
                  <p className="text-muted-foreground">
                    Privacy questions? Contact us via our{' '}
                    <a href="/contact" className="text-primary hover:underline">
                      booking form
                    </a>.
                  </p>
                </section>

              </div>
            </ScrollReveal>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Privacy;
