import ScrollReveal from '@/components/ScrollReveal';
import SEO, { schemas } from '@/components/SEO';

const Privacy = () => {
  return (
    <div className="min-h-screen bg-[#0F0F0F]">
      <SEO 
        title="Privacy Policy – AERELION Systems"
        description="Privacy Policy for AERELION Systems. We process data only to deliver managed automation services. Credentials encrypted at rest."
        canonicalUrl="/privacy"
        structuredData={schemas.breadcrumb([
          { name: 'Home', url: '/' },
          { name: 'Privacy Policy', url: '/privacy' }
        ])}
      />
      
      <main className="pt-8">
        <section className="section-padding">
          <div className="container-main max-w-3xl">
            <ScrollReveal>
              <span className="font-mono text-[10px] text-[#39FF14]/50 uppercase tracking-[0.25em] mb-3 block">
                // DATA GOVERNANCE PROTOCOL
              </span>
              <h1 className="font-mono text-3xl md:text-4xl font-semibold text-[#E0E0E0] mb-2">
                Privacy Policy
              </h1>
              <p className="font-mono text-xs text-white/20 mb-10">
                Last updated: January 2026
              </p>
            </ScrollReveal>

            <ScrollReveal delay={0.1}>
              <div className="space-y-8">
                {[
                  { title: 'Operational Model', content: 'AERELION Systems is a managed infrastructure operator. We configure, stabilize, and operate automation protocols on behalf of authorized entities. We access systems only to deliver agreed services—nothing more.' },
                  { title: 'Data Collection', content: null, list: ['Engagement information: Name, email, entity details submitted through intake terminals.', 'Credentials: Access tokens and authorization provided to enable protocol operation.', 'Operational data: Logs and metrics generated by running protocols on your behalf.'] },
                  { title: 'Data Usage', content: null, list: ['To configure and operate protocols on your behalf.', 'To troubleshoot issues and optimize protocol performance.', 'To communicate about engagement status and provide operational support.'], note: 'We do not sell, share, or monetize your data.' },
                  { title: 'Credential Security', content: null, list: ['Credentials encrypted at rest (AES-256-GCM) and in transit (TLS 1.3).', 'Least-privilege access — only what is required for protocol operation.', 'You can revoke authorization at any time.'] },
                  { title: 'Data Retention', content: 'Operational data retained only as long as necessary. Logs are regularly purged. After engagement ends, credentials are deleted unless ongoing monitoring is authorized.' },
                  { title: 'Your Rights', content: null, list: ['Request a summary of data held about your engagement.', 'Request deletion of your data after engagement ends.', 'Revoke access to connected accounts at any time.'] },
                  { title: 'Third-Party Systems', content: 'Protocols may interact with third-party services (CRM, email, project management). Those services have their own privacy policies.' },
                  { title: 'Contact', content: 'Privacy inquiries: contact@aerelion.systems' },
                ].map((section, i) => (
                  <div key={i} className="border-b border-white/5 pb-6">
                    <h2 className="font-mono text-sm font-semibold text-[#E0E0E0] mb-3">{section.title}</h2>
                    {section.content && <p className="font-sans text-sm text-white/35 leading-relaxed">{section.content}</p>}
                    {section.list && (
                      <ul className="space-y-2">
                        {section.list.map((item, j) => (
                          <li key={j} className="flex items-start gap-2 text-sm text-white/35 font-sans">
                            <span className="font-mono text-[10px] text-[#39FF14]/30 mt-1">▸</span>
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    )}
                    {section.note && <p className="font-sans text-sm text-white/50 mt-3 font-medium">{section.note}</p>}
                  </div>
                ))}
              </div>
            </ScrollReveal>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Privacy;
