import { Helmet } from 'react-helmet-async';

const SECTIONS = [
  { title: 'Operational Model', content: 'AERELION is a managed automation operator. We configure, deploy, and operate automation systems on behalf of authorized entities. We access systems only to deliver agreed services.' },
  { title: 'Data Collection', list: ['Engagement information: Name, email, company details submitted through intake forms.', 'Credentials: Access tokens and authorization provided to enable system operation.', 'Operational data: Logs and metrics generated by running systems on your behalf.'] },
  { title: 'Data Usage', list: ['To configure and operate systems on your behalf.', 'To troubleshoot issues and optimize performance.', 'To communicate about engagement status and provide support.'], note: 'We do not sell, share, or monetize your data.' },
  { title: 'Security', list: ['Credentials encrypted at rest (AES-256-GCM) and in transit (TLS 1.3).', 'Least-privilege access — only what is required for operation.', 'You can revoke authorization at any time.'] },
  { title: 'Data Retention', content: 'Operational data retained only as long as necessary. After engagement ends, credentials are deleted unless ongoing monitoring is authorized.' },
  { title: 'Your Rights', list: ['Request a summary of data held about your engagement.', 'Request deletion of your data after engagement ends.', 'Revoke access to connected accounts at any time.'] },
  { title: 'Contact', content: 'Privacy inquiries: contact@aerelion.com' },
];

const Privacy = () => (
  <main className="pt-32 pb-20">
    <Helmet>
      <title>Privacy Policy – AERELION</title>
      <meta name="description" content="Privacy Policy for AERELION. We process data only to deliver managed automation services." />
    </Helmet>
    <div className="max-w-3xl mx-auto px-6 md:px-12">
      <p className="text-xs font-mono uppercase tracking-[0.25em] text-primary mb-4">Legal</p>
      <h1 className="font-display text-3xl md:text-4xl mb-2">Privacy Policy</h1>
      <p className="text-sm text-muted-foreground mb-12">Last updated: February 2026</p>
      <div className="space-y-8">
        {SECTIONS.map((s, i) => (
          <div key={i} className="border-b border-border pb-6">
            <h2 className="text-sm font-semibold text-foreground mb-3">{s.title}</h2>
            {s.content && <p className="text-sm text-muted-foreground leading-relaxed">{s.content}</p>}
            {s.list && (
              <ul className="space-y-2">
                {s.list.map((item, j) => (
                  <li key={j} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <span className="text-primary mt-0.5">—</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            )}
            {s.note && <p className="text-sm text-foreground/60 mt-3 font-medium">{s.note}</p>}
          </div>
        ))}
      </div>
    </div>
  </main>
);

export default Privacy;
